openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a REST API for managing contacts and user authentication.
tags:
  - name: Contacts
    description: Contact operations
  - name: Auth
    description: Registration and authorization
servers:
  - url: http://localhost:3000

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/get.yaml
    post:
      $ref: ../swagger/paths/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/getId.yaml
    patch:
      $ref: ../swagger/paths/patch.yaml
    delete:
      $ref: ../swagger/paths/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
